[build]
  command = "pip install -r requirements.txt"
  publish = "public" # Tạo một thư mục trống tên 'public' ở gốc nếu bạn không có web

[functions]
  directory = "netlify/functions"

[functions."job"]
  # Chạy lúc 9h, 14h, 22h VN (tương ứng 2h, 7h, 15h UTC)
  schedule = "0 2,7,15 * * *"